import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    scrollContent: {
        flex: 1,
    },
    content: {
        padding: 24,
    },
    pageContent: {
        flex: 1,
    },
    visibleTab: {
        flex: 1,
    },
    hiddenTab: {
        display: 'none',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 24,
        paddingTop: 48,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    backButton: {
        width: 40,
        height: 40,
        backgroundColor: '#f3f4f6',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerText: {
        flex: 1,
        marginLeft: 12,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1f2937',
    },
    subtitle: {
        fontSize: 14,
        color: '#6b7280',
    },
    selectorButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    tabsContainer: {
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabActive: {
        borderBottomColor: '#059669',
    },
    tabText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#6b7280',
    },
    tabTextActive: {
        color: '#059669',
        fontWeight: '600',
    },
    translationToggleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#ffffff',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    translationToggleLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    smallToggleButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        backgroundColor: '#e5e7eb',
    },
    smallToggleButtonActive: {
        backgroundColor: '#059669',
    },
    smallToggleText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#6b7280',
    },
    smallToggleTextActive: {
        color: '#ffffff',
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: '#6b7280',
    },
    errorText: {
        fontSize: 16,
        color: '#ef4444',
        textAlign: 'center',
        marginBottom: 16,
    },
    retryButton: {
        backgroundColor: '#059669',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 8,
    },
    retryText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
    },
    progressCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    progressHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    progressLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    progressValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#059669',
    },
    progressBarBg: {
        height: 8,
        backgroundColor: '#e5e7eb',
        borderRadius: 4,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#059669',
        borderRadius: 4,
    },
    verseCard: {
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 32,
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    verseNumber: {
        width: 48,
        height: 48,
        backgroundColor: '#d1fae5',
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginBottom: 24,
    },
    verseNumberText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#059669',
    },
    arabicText: {
        fontSize: 32,
        lineHeight: 56,
        textAlign: 'center',
        color: '#1f2937',
        marginBottom: 16,
        writingDirection: 'rtl',
    },
    audioButton: {
        width: 48,
        height: 48,
        backgroundColor: '#059669',
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginBottom: 32,
    },
    transliterationBox: {
        backgroundColor: '#d1fae5',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    sectionLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6b7280',
        marginBottom: 4,
    },
    transliterationText: {
        fontSize: 16,
        color: '#1f2937',
        fontStyle: 'italic',
    },
    translationHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    toggleButton: {
        paddingHorizontal: 16,
        paddingVertical: 4,
        borderRadius: 20,
        backgroundColor: '#e5e7eb',
    },
    toggleButtonActive: {
        backgroundColor: '#059669',
    },
    toggleText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6b7280',
    },
    toggleTextActive: {
        color: '#ffffff',
    },
    translationBox: {
        backgroundColor: '#dbeafe',
        borderRadius: 16,
        padding: 16,
    },
    translationText: {
        fontSize: 16,
        color: '#1f2937',
    },
    navigationButtons: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    navButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#ffffff',
        paddingVertical: 16,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    navButtonDisabled: {
        backgroundColor: '#e5e7eb',
    },
    navButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
    },
    navButtonTextDisabled: {
        color: '#9ca3af',
    },
    markReadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#059669',
        paddingVertical: 16,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    markReadButtonCompleted: {
        backgroundColor: '#6b7280',
        opacity: 0.7,
    },
    markReadText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    signInPrompt: {
        backgroundColor: '#fef3c7',
        padding: 16,
        borderRadius: 16,
        alignItems: 'center',
    },
    signInPromptText: {
        fontSize: 14,
        color: '#92400e',
    },
    pageListContent: {
        paddingTop: 8,
        paddingBottom: 16,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        maxHeight: '85%',
    },
    modalScrollView: {
        maxHeight: 450,
    },
    modalScrollContent: {
        flexGrow: 1,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1f2937',
    },
    modalClose: {
        fontSize: 24,
        color: '#6b7280',
        fontWeight: 'bold',
    },
    selectorsRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 20,
    },
    selectorColumn: {
        flex: 1,
    },
    selectorLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 12,
        textAlign: 'center',
    },
    selectorScroll: {
        maxHeight: 350,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        backgroundColor: '#f9fafb',
    },
    selectorItem: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    selectorItemActive: {
        backgroundColor: '#d1fae5',
    },
    selectorItemNumber: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6b7280',
        minWidth: 30,
    },
    selectorItemText: {
        flex: 1,
    },
    selectorItemName: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    selectorItemArabic: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 2,
    },
    selectorItemVerseNumber: {
        fontSize: 18,
        fontWeight: '600',
        color: '#6b7280',
        textAlign: 'center',
        width: '100%',
    },
    selectorItemTextActive: {
        color: '#059669',
    },
    modalConfirmButton: {
        backgroundColor: '#059669',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    modalConfirmText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
    },
    mushafListContent: {
        paddingTop: 8,
        paddingBottom: 16,
        paddingHorizontal: 8,
    },
    mushafVerseContainer: {
        marginBottom: 8,
    },
    mushafSourateHeader: {
        alignItems: 'center',
        marginVertical: 24,
        paddingHorizontal: 16,
    },
    mushafSourateName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#059669',
        textAlign: 'center',
        marginBottom: 12,
    },
    mushafDivider: {
        width: '60%',
        height: 2,
        backgroundColor: '#d1fae5',
        borderRadius: 1,
    },
    mushafVerse: {
        backgroundColor: '#ffffff',
        padding: 20,
        marginHorizontal: 8,
        marginVertical: 4,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    mushafText: {
        fontSize: 26,
        lineHeight: 50,
        textAlign: 'right',
        color: '#1f2937',
        writingDirection: 'rtl',
        flex: 1,
    },
    mushafNumber: {
        position: 'absolute',
        top: 8,
        left: 8,
        width: 28,
        height: 28,
        backgroundColor: '#d1fae5',
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 12,
        fontWeight: '600',
        color: '#059669',
        textAlign: 'center',
        lineHeight: 28,
    },
    mushafAudioButton: {
        width: 32,
        height: 32,
        backgroundColor: '#d1fae5',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 8,
        marginTop: 8,
    },
    mushafAudioButtonPlaying: {
        backgroundColor: '#059669',
    },
    pageScrollContent: {
        flex: 1,
    },
    mushafScrollContent: {
        flex: 1,
    },
    sourateHeader: {
        alignItems: 'center',
        padding: 24,
        backgroundColor: '#ffffff',
        borderBottomWidth: 3,
        borderBottomColor: '#059669',
        marginBottom: 16,
    },
    sourateHeaderNumber: {
        fontSize: 48,
        fontWeight: 'bold',
        color: '#059669',
    },
    sourateHeaderName: {
        fontSize: 32,
        color: '#1f2937',
        marginTop: 8,
        textAlign: 'center',
    },
    sourateHeaderTranslation: {
        fontSize: 20,
        color: '#6b7280',
        marginTop: 4,
    },
    sourateNavigation: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        padding: 16,
        paddingBottom: 32,
    },
    sourateNavButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        padding: 16,
        borderRadius: 12,
        gap: 8,
        borderWidth: 2,
        borderColor: '#059669',
    },
    sourateNavButtonDisabled: {
        borderColor: '#e5e7eb',
        backgroundColor: '#f9fafb',
    },
    sourateNavButtonContent: {
        flex: 1,
    },
    sourateNavButtonLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#059669',
    },
    sourateNavButtonName: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 2,
    },
    sourateNavButtonTextDisabled: {
        color: '#9ca3af',
    },
});
